version: '3.8'

services:
  auth:
    container_name: auth_container
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - 3000:3000
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - dripp_network
    depends_on:
      - mongo

  brand:
    container_name: brand_container
    build:
      context: .
      dockerfile: ./apps/brand/Dockerfile
      target: development
    command: yarn start:dev brand
    env_file:
      - ./apps/brand/.env
    ports:
      - 2000:2000
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - dripp_network
    depends_on:
      - mongo

  chat:
    container_name: chat_container
    build:
      context: .
      dockerfile: ./apps/chat/Dockerfile
      target: development
    command: yarn start:dev chat
    env_file:
      - ./apps/chat/.env
    ports:
      - 5000:5000
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - dripp_network
    depends_on:
      - mongo

  notification:
    container_name: notification_container
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
      target: development
    command: yarn start:dev notification
    env_file:
      - ./apps/notification/.env
    ports:
      - 1000:1000
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - dripp_network
    depends_on:
      - mongo

  wallet:
    container_name: wallet_container
    build:
      context: .
      dockerfile: ./apps/wallet/Dockerfile
      target: development
    command: yarn start:dev wallet
    env_file:
      - ./apps/wallet/.env
    ports:
      - 4000:4000
    volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - dripp_network
    depends_on:
      - mongo
      - redis  

  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile
    container_name: webserver_container
    ports:
      - 80:80
      - 443:443
    networks:
      - dripp_network
    restart: always
    depends_on:
      - auth
      - wallet
      - brand
      - notification
  
  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: phoenix
      MONGO_INITDB_ROOT_PASSWORD: phoenix
    ports:
      - 27017:27017
    volumes:
      - ./database/mongo:/data/db
    networks:
      - dripp_network
    restart: always

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./database/redis/data:/data
    networks:
      - dripp_network

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq_container
    volumes:
      - "./database/rmq:/var/lib/rabbitmq/mnesia/"
    ports:
      - 5672:5672
    networks:
      - dripp_network
    

networks:
  dripp_network:
    external: true